image: microsoft/dotnet:latest

stages:
  - build
  - publish

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

publish:
  stage: publish
  script:
    - dotnet build
    - dotnet publish
    - nuget push SupplyCollectorDataLoader/bin/Debug/*.nupkg $NUGET_KEY -Source https://www.myget.org/F/s2/api/v2/package

